// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvvlRLOYXCdzyW5mGyA4keSvwDO-hDEBQ',
    appId: '1:299629767442:web:7a4e129d214f01dcc061cb',
    messagingSenderId: '299629767442',
    projectId: 'elarosgp4',
    authDomain: 'elarosgp4.firebaseapp.com',
    storageBucket: 'elarosgp4.firebasestorage.app',
    measurementId: 'G-WFM0H4NCC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlRsISKbHjYWBTH1Mj9VPK_Q3hQKxLeGo',
    appId: '1:299629767442:android:c2657096ae6c8c26c061cb',
    messagingSenderId: '299629767442',
    projectId: 'elarosgp4',
    storageBucket: 'elarosgp4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8iXz5WLxzH3GqjEGfqGI9FQ8QLspzhG8',
    appId: '1:299629767442:ios:5ef0cafddae25214c061cb',
    messagingSenderId: '299629767442',
    projectId: 'elarosgp4',
    storageBucket: 'elarosgp4.firebasestorage.app',
    iosBundleId: 'com.example.elarosGp4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8iXz5WLxzH3GqjEGfqGI9FQ8QLspzhG8',
    appId: '1:299629767442:ios:5ef0cafddae25214c061cb',
    messagingSenderId: '299629767442',
    projectId: 'elarosgp4',
    storageBucket: 'elarosgp4.firebasestorage.app',
    iosBundleId: 'com.example.elarosGp4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvvlRLOYXCdzyW5mGyA4keSvwDO-hDEBQ',
    appId: '1:299629767442:web:6434c8f5da9e82bcc061cb',
    messagingSenderId: '299629767442',
    projectId: 'elarosgp4',
    authDomain: 'elarosgp4.firebaseapp.com',
    storageBucket: 'elarosgp4.firebasestorage.app',
    measurementId: 'G-4JRYJMPVV7',
  );
}
